//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorseDBEntities1 : DbContext
    {
        public HorseDBEntities1()
            : base("name=HorseDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bein> Bein { get; set; }
        public virtual DbSet<Foto> Foto { get; set; }
        public virtual DbSet<Grafik> Grafik { get; set; }
        public virtual DbSet<Koerper> Koerper { get; set; }
        public virtual DbSet<Kopf> Kopf { get; set; }
        public virtual DbSet<Merkmale> Merkmale { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Pferd> Pferd { get; set; }
    }
}
