//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koerper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Koerper()
        {
            this.Merkmale = new HashSet<Merkmale>();
        }
    
        public int id { get; set; }
        public string farbe { get; set; }
        public string abzeichen { get; set; }
        public string maehne { get; set; }
        public string wirbel { get; set; }
        public string dominanz { get; set; }
        public string weiteremerkmale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Merkmale> Merkmale { get; set; }
    }
}
