//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merkmale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merkmale()
        {
            this.Pferd = new HashSet<Pferd>();
        }
    
        public int id { get; set; }
        public Nullable<int> kopf { get; set; }
        public Nullable<int> vorderbeinlinks { get; set; }
        public Nullable<int> vorderbeinrechts { get; set; }
        public Nullable<int> hinterbeinlinks { get; set; }
        public Nullable<int> hinterbeinrechts { get; set; }
        public Nullable<int> koerper { get; set; }
        public string besonderheiten { get; set; }
        public string beurteilung { get; set; }
    
        public virtual Bein Bein { get; set; }
        public virtual Bein Bein1 { get; set; }
        public virtual Bein Bein2 { get; set; }
        public virtual Bein Bein3 { get; set; }
        public virtual Koerper Koerper1 { get; set; }
        public virtual Kopf Kopf1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pferd> Pferd { get; set; }
    }
}
