//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Pferd = new HashSet<Pferd>();
            this.Pferd1 = new HashSet<Pferd>();
        }
    
        public int id { get; set; }
        public string nachname { get; set; }
        public string vorname { get; set; }
        public string titelpre { get; set; }
        public string titelpost { get; set; }
        public Nullable<System.DateTime> geburtsdatum { get; set; }
        public string strasse { get; set; }
        public string hausnummer { get; set; }
        public string postleitzahl { get; set; }
        public string ort { get; set; }
        public string land { get; set; }
        public string hofname { get; set; }
        public string telefonnummer { get; set; }
        public string mobiltelefon { get; set; }
        public string email { get; set; }
        public Nullable<bool> mitgliedsbeitragbezahlt { get; set; }
        public Nullable<System.DateTime> mitgliedseit { get; set; }
        public string mitgliedschaftsart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pferd> Pferd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pferd> Pferd1 { get; set; }
    }
}
