//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pferd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pferd()
        {
            this.Foto = new HashSet<Foto>();
            this.Grafik = new HashSet<Grafik>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string herkunft { get; set; }
        public string geschlecht { get; set; }
        public System.DateTime geburtsdatum { get; set; }
        public string geburtsort { get; set; }
        public string farbeundabzeichen { get; set; }
        public string ueln { get; set; }
        public string mikrochipnummer { get; set; }
        public string brandnummer { get; set; }
        public string dna { get; set; }
        public string pferdepassnummer { get; set; }
        public Nullable<System.DateTime> pferdepassausstellungsdatum { get; set; }
        public string registernummer { get; set; }
        public string idnummer { get; set; }
        public string zuchtbuchnummer { get; set; }
        public Nullable<bool> schlachtpferd { get; set; }
        public string abgangsstandort { get; set; }
        public Nullable<bool> lebend { get; set; }
        public string zuchtwert { get; set; }
        public string zuchtbuch { get; set; }
        public string fohlennummer { get; set; }
        public Nullable<int> zuechter { get; set; }
        public Nullable<int> besitzer { get; set; }
        public Nullable<int> merkmale { get; set; }
        public Nullable<int> mutter { get; set; }
        public Nullable<int> vater { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foto> Foto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grafik> Grafik { get; set; }
        public virtual Merkmale Merkmale1 { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual Pferd Pferd1 { get; set; }
        public virtual Pferd Pferd2 { get; set; }
        public virtual Pferd Pferd11 { get; set; }
        public virtual Pferd Pferd3 { get; set; }
    }
}
